package kitsune

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Writes the shared VM flags to a file the host process reads at startup, so the
 * flags the AOT cache was built with and the flags it is consumed with cannot
 * drift apart.
 */
abstract class WriteVmOptionsTask : DefaultTask() {

    @get:Input
    abstract val vmOptions: ListProperty<String>

    @get:OutputFile
    abstract val optionsFile: RegularFileProperty

    @TaskAction
    fun run() {
        val text = buildString {
            appendLine("# Generated by :writeVmOptions — do not edit.")
            appendLine("# Edit the kitsune { vmOptions } block in build.gradle.kts instead.")
            appendLine("# These must match the flags the AOT cache was recorded with.")
            vmOptions.get().forEach { appendLine(it) }
        }
        optionsFile.get().asFile.apply {
            parentFile.mkdirs()
            writeText(text)
        }
    }
}
