package revxrsal.kitsune.codegen.typescript

import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSNode
import revxrsal.kitsune.codegen.functions.ExportedFun
import revxrsal.kitsune.codegen.functions.argumentsSerialName

/**
 * An `@ExportFunction`, paired with the ordinal the bridge dispatches it under.
 *
 * [exportedName] is no longer on the wire — the ordinal replaced it — but it is
 * still what the binding is *called*, and what a diagnostic names.
 */
class BoundFunction(val ordinal: Int, val exportedName: String, val function: ExportedFun)

/** An `@ExportEvent` class, paired with the ordinal it travels under. */
class BoundEvent(val ordinal: Int, val id: String, val declaration: KSClassDeclaration)

/**
 * Words TypeScript will not accept as a declaration name.
 *
 * Only the ones an exported name could plausibly collide with — `delete`,
 * `new`, `default` are all reasonable things to call a bridge function, and all
 * of them produce a file that does not parse.
 */
private val RESERVED = setOf(
    "await", "break", "case", "catch", "class", "const", "continue", "debugger", "default",
    "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for", "function",
    "if", "import", "in", "instanceof", "new", "null", "return", "super", "switch", "this",
    "throw", "true", "try", "typeof", "var", "void", "while", "with", "yield",
)

private val IDENTIFIER = Regex("""[A-Za-z_$][A-Za-z0-9_$]*""")

/**
 * Renders the whole bindings file.
 *
 * One file rather than one per export, for the same reason the Kotlin side
 * aggregates: the set is what the frontend imports from, and a directory of
 * single-declaration modules would make every rename a churn of import lines.
 *
 * Sections are assembled in dependency order — the types the signatures mention
 * are emitted before the signatures — but only as a courtesy to a reader.
 * TypeScript hoists both interfaces and function declarations, so nothing here
 * depends on the order.
 */
fun renderBindings(
    functions: List<BoundFunction>,
    events: List<BoundEvent>,
    bridgeImport: String,
    logger: KSPLogger,
): String {
    val types = TsTypes(logger)

    // Rendered first, and emitted last: both of these fill the type registry as
    // a side effect, and the declarations they reached have to be known before
    // the file can be laid out.
    val renderedFunctions = functions.mapNotNull { renderFunction(it, types, logger) }
    val renderedEvents = events.mapNotNull { renderEvent(it, types, logger) }

    val sections = mutableListOf(HEADER)

    // Conditional because the frontend compiles with `noUnusedLocals`: an
    // unused `Bridge` import in a module that exports nothing is not a warning
    // there, it is a build failure. Events reach for it too — `emit` and
    // `listen` are forwards to the bridge, same as a function call.
    if (renderedFunctions.isNotEmpty() || renderedEvents.isNotEmpty()) {
        sections += "import {Bridge} from '$bridgeImport'"
    }
    if (renderedEvents.isNotEmpty()) {
        sections += "/** Stops a subscription started with `listen`. */\nexport type Unlisten = () => void"
    }

    types.declarations().takeIf { it.isNotEmpty() }?.let { declarations ->
        sections += banner("types")
        sections += declarations
    }
    if (renderedFunctions.isNotEmpty()) {
        sections += banner("functions")
        sections += renderedFunctions
    }
    if (renderedEvents.isNotEmpty()) {
        sections += banner("events")
        sections += renderedEvents
    }

    return sections.joinToString("\n\n", postfix = "\n")
}

private val HEADER = """
    // Bindings for every `@ExportFunction` and `@ExportEvent` in the Kotlin
    // module. Generated by Kitsune's KSP processor — do not edit.
    //
    // Argument objects mirror the `SerialDescriptor` the generated Kotlin
    // wrapper decodes with, element for element: a `?` here is a parameter the
    // Kotlin declaration gives a default, and leaving it out is what makes that
    // default apply. Passing `undefined` explicitly is not the same thing — the
    // key still reaches the decoder — so omit it rather than spelling it out.
    //
    // The numbers below are wire ordinals: the index the Kotlin side looks the
    // export up at, written into the head of the payload instead of a name. They
    // are assigned by sorting the exported names, so adding an export renumbers
    // the ones after it — which is harmless only because both halves are
    // regenerated together. Never hand-write one.
""".trimIndent()

private fun banner(title: String): String =
    "// ---- $title " + "-".repeat(72 - title.length) + "-"

/**
 * One exported function: its argument object, and the call that forwards to it.
 *
 * The wrapper is a plain forward to [Bridge.call] with the ordinal baked in —
 * the encoding, the transport and the reply all belong to the bridge, and
 * duplicating any of it per function would be one more place for the two sides
 * to drift.
 */
private fun renderFunction(bound: BoundFunction, types: TsTypes, logger: KSPLogger): String? {
    val name = bound.exportedName
    if (!name.isBindable(logger, "function", bound.function.function)) return null

    val function = bound.function
    val returns = function.function.returnType?.resolve()
        ?.let { types.typeOf(it, function.function) }
        ?: "void"

    val documentation = "/** `${function.qualifiedName}` */"
    val ordinal = bound.ordinal
    if (function.parameters.isEmpty()) {
        return """
            |$documentation
            |export function $name(): Promise<$returns> {
            |  return Bridge.call($ordinal, {})
            |}
        """.trimMargin()
    }

    // Named after the descriptor's serial name rather than after the function,
    // so a payload rejected by the Kotlin decoder names the same thing the
    // caller was looking at when they built it.
    val argumentsType = function.argumentsSerialName
    val fields = function.parameters.joinToString("\n") { parameter ->
        val optional = if (parameter.hasDefault) "?" else ""
        "  ${quote(parameter.name)}$optional: ${types.typeOf(parameter.type, parameter.declaration)}"
    }

    // Every parameter defaulted means the whole object may be left out, which is
    // the difference between `version()` and `reverse()` reading naturally.
    val default = if (function.parameters.all { it.hasDefault }) " = {}" else ""

    return """
        |$documentation
        |export interface $argumentsType {
        |$fields
        |}
        |
        |$documentation
        |export function $name(args: $argumentsType$default): Promise<$returns> {
        |  return Bridge.call($ordinal, args)
        |}
    """.trimMargin()
}

/**
 * One exported event, as a value carrying both directions of it.
 *
 * The const shares its name with the payload interface, which TypeScript allows
 * — an interface lives in the type namespace and a const in the value one — and
 * which is what lets `ButtonClicked` be both the thing you describe a handler
 * with and the thing you call `.listen` on.
 *
 * Both directions are plain forwards to the bridge with the ordinal baked in,
 * exactly as a function binding is. The id comes along for diagnostics only:
 * nothing dispatches on it any more.
 */
private fun renderEvent(bound: BoundEvent, types: TsTypes, logger: KSPLogger): String? {
    val payload = types.typeOf(bound.declaration.asStarProjectedType(), bound.declaration)
    // `unknown` means the payload could not be described; the const is still
    // worth emitting, and it is named after the class either way.
    val name = if (payload == "unknown") bound.declaration.simpleName.asString() else payload
    if (!name.isBindable(logger, "event", bound.declaration)) return null

    val qualifiedName = bound.declaration.qualifiedName?.asString() ?: name
    return """
        |/** `$qualifiedName` */
        |export const $name = {
        |  /** The ordinal this event travels under, on both sides of the bridge. */
        |  ordinal: ${bound.ordinal},
        |
        |  /** The id it was declared with. Diagnostics only — the wire carries the ordinal. */
        |  id: '${bound.id}',
        |
        |  /** Sends the event to Kotlin, where every `@Listener` for it runs. */
        |  emit: (event: $payload): Promise<void> => Bridge.emit(${bound.ordinal}, event),
        |
        |  /** Subscribes to the event; call the result to stop. */
        |  listen: (handler: (event: $payload) => void): Unlisten =>
        |    Bridge.listen(${bound.ordinal}, handler as (event: unknown) => void),
        |}
    """.trimMargin()
}

/**
 * Whether this name can be declared in TypeScript at all.
 *
 * A warning rather than an error: the Kotlin side is perfectly entitled to
 * export a function called `delete`, the host dispatches it by string and does
 * not care, and failing the build over what one binding is *named* would make
 * the TypeScript generator able to break a working app.
 */
private fun String.isBindable(
    logger: KSPLogger,
    kind: String,
    node: KSNode,
): Boolean {
    val bindable = IDENTIFIER.matches(this) && this !in RESERVED
    if (!bindable) {
        logger.warn(
            "Kitsune bindings: '$this' is not a usable TypeScript name, so no binding is " +
                "generated for this $kind. It stays callable by name through Bridge.call.",
            node,
        )
    }
    return bindable
}
