// Bindings for every `@ExportFunction` and `@ExportEvent` in the Kotlin
// module. Generated by Kitsune's KSP processor. Do not edit.
//
// Argument objects mirror the `SerialDescriptor` the generated Kotlin
// wrapper decodes with, element for element: a `?` here is a parameter the
// Kotlin declaration gives a default, and leaving it out is what makes that
// default apply. Passing `undefined` explicitly is not the same thing (the
// key still reaches the decoder), so omit it rather than spelling it out.
//
// The numbers below are wire ordinals: the index the Kotlin side looks the
// export up at, written into the head of the payload instead of a name. They
// are assigned by sorting the exported names, so adding an export renumbers
// the ones after it, which is harmless only because both halves are
// regenerated together. Never hand-write one.

import {Bridge} from './Bridge'

/** Stops a subscription started with `listen`. */
export type Unlisten = () => void

// ---- types --------------------------------------------------------------------

/** `revxrsal.kitsune.SomeEvent` */
export interface SomeEvent {
  id: number
  name?: string
}

// ---- functions ----------------------------------------------------------------

/** `revxrsal.kitsune.emitEvent` */
export function emitEvent(): Promise<void> {
  return Bridge.call(0, {})
}

/** `revxrsal.kitsune.warmUp` */
export function warmUp(): Promise<void> {
  return Bridge.call(1, {})
}

// ---- events -------------------------------------------------------------------

/** `revxrsal.kitsune.SomeEvent` */
export const SomeEvent = {
  /** The ordinal this event travels under, on both sides of the bridge. */
  ordinal: 0,

  /** The id it was declared with. Diagnostics only; the wire carries the ordinal. */
  id: 'SomeEvent',

  /** Sends the event to Kotlin, where every `@Listener` for it runs. */
  emit: (event: SomeEvent): Promise<void> => Bridge.emit(0, event),

  /** Subscribes to the event; call the result to stop. */
  listen: (handler: (event: SomeEvent) => void): Unlisten =>
    Bridge.listen(0, handler as (event: unknown) => void),
}
